// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {search} from '../models';

export function AddText(arg1:string,arg2:string):Promise<void>;

export function AddURL(arg1:string):Promise<void>;

export function ReadTextFile(arg1:string):Promise<string>;

export function Search(arg1:string):Promise<Array<search.SearchResult>>;
