// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddContent(arg1:string):Promise<void>;

export function Search(arg1:string):Promise<Array<main.SimResult>>;
