// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddText(arg1, arg2) {
  return window['go']['main']['App']['AddText'](arg1, arg2);
}

export function AddURL(arg1) {
  return window['go']['main']['App']['AddURL'](arg1);
}

export function ReadTextFile(arg1) {
  return window['go']['main']['App']['ReadTextFile'](arg1);
}

export function Search(arg1) {
  return window['go']['main']['App']['Search'](arg1);
}
